baseurl = "http://coldwalker.com/"
title = "Hacking Management"
languageCode = "en-us"
disqusShortname = "ralin"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
MetaDataFormat = "yaml"

[author]
    name = "Steve Francia"

[indexes]
    tag = "tags"
    topic = "topics"

