baseURL = "https://coldwalker.com/"
languageCode = "zh-CN"
title = "凛冬夜行"
theme="hugo_theme_beg"
canonifyurls = true
pygmentsStyle = "monokai"
pygmentsUseClasses = false
hasCJKLanguage = true
enableRobotsTXT = true
PygmentsCodeFences = true
image = "images/me.JPG"
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."
disqusShortname = "ralin"
googleAnalytics = "UA-116113253-1"

[permalinks]
post = "/:year/:month/:/:filename/"

[[menu.main]]
    name = "about Me"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/2018/03/about/"

[params]
  dateformat = "2006-01-02" # Optional
  MonthFormat = "2006-01"
  changyan = true
  changyanId = "cytwFfxww"
  changyanConf = "prod_36cf3e358f9305067d10b0652031cb07"
  baiduTongji = "f13b34958e759c7a5400b5cdf455f21c"
  Archive = "Archive"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]
